<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>password_generator</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>pg</AssemblyName>
		<Version>1.0.0</Version>
		<Authors>Meraj Esmaeili</Authors>
		<Description>Password Generator CLI Tool</Description>
	</PropertyGroup>

</Project>
