<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>password_generator</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>pg</AssemblyName>
		<PackAsTool>true</PackAsTool>
		<ToolCommandName>pg</ToolCommandName>
		<PackageOutputPath>..\artifacts\nupkg</PackageOutputPath>
		<PackageId>password-generator</PackageId>
		<Version>2.0.0</Version>
		<Authors>Meraj Esmaeili</Authors>
		<Description>Password Generator CLI Tool</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.49.1" />
		<PackageReference Include="TextCopy" Version="6.2.1" />
	</ItemGroup>

</Project>